# Definir el pool de agentes donde se ejecutará el pipeline
pool:
  vmImage: 'windows-latest'

# Definir los stages del pipeline
stages:
- stage: HolaMundo
  displayName: 'Hola Mundo'
  jobs:
  - job: EjecutarScript
    displayName: 'Ejecutar Script de Hola Mundo'
    steps:
    - script: echo "Hola mundo"
